In [4]:
import tensorflow as tf
tf.set_random_seed(777)

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
x_data_test = [[1, 11, 7, 9],
               [1, 3, 4, 3],
               [1, 1, 0, 1]]

nb_classes = 3

X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 3])
W = tf.Variable(tf.random_normal([4,nb_classes]), name = "weight")
b = tf.Variable(tf.random_normal([nb_classes]), name = "bias")

hypothesis = tf.nn.softmax(tf.matmul(X,W)+ b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val,_ = sess.run([cost,optimizer], feed_dict = {X : x_data, Y : y_data})
  if step % 200 == 0:
    print(step, cost_val)
    
print('--------------')
a = sess.run(hypothesis, feed_dict = {X : [[1,11,7,9]]})
print(a, sess.run(tf.argmax(a, 1)))
print('--------------')
b = sess.run(hypothesis, feed_dict = {X : [[1,3,4,3]]})
print(b, sess.run(tf.argmax(b, 1)))
print('--------------')
c = sess.run(hypothesis, feed_dict = {X : [[1,1,0,1]]})
print(c, sess.run(tf.argmax(c, 1)))
print('--------------')
all = sess.run(hypothesis, feed_dict = {X :  [[1, 11, 7, 9],
               [1, 3, 4, 3],
               [1, 1, 0, 1]]})
print(all, sess.run(tf.argmax(all,1)))

0 3.862811
200 0.54248315
400 0.42817527
600 0.33045882
800 0.25154757
1000 0.224703
1200 0.2037518
1400 0.18636793
1600 0.17168146
1800 0.15910137
2000 0.14820315
--------------
[[9.900534e-04 9.990007e-01 9.251602e-06]] [1]
--------------
[[0.9407002  0.05359482 0.00570504]] [0]
--------------
[[9.9969704e-09 3.1985613e-04 9.9968016e-01]] [2]
--------------
[[9.9005341e-04 9.9900073e-01 9.2516020e-06]
 [9.4070017e-01 5.3594828e-02 5.7050413e-03]
 [9.9969713e-09 3.1985613e-04 9.9968016e-01]] [1 0 2]
